/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.model.User;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.DragAndDropPanel;
import hr.algebra.view.EditActorDirectorPanel;
import hr.algebra.view.EditMoviePanel;
import hr.algebra.view.UploadMoviePanel;

/**
 *
 * @author antoanne
 */
public class MovieManager extends javax.swing.JFrame {

    private static final String ADMIN = "admin";

    /**
     * Creates new form MovieManager
     */
    public MovieManager(User user) {
        initComponents();
        setDisplay(user);
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miContact = new javax.swing.JMenuItem();
        miAboutUs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 750));

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.META_DOWN_MASK));
        miLogout.setMnemonic('L');
        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('H');
        jMenu2.setText("Help");

        miContact.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.META_DOWN_MASK));
        miContact.setMnemonic('C');
        miContact.setText("Contact");
        miContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContactActionPerformed(evt);
            }
        });
        jMenu2.add(miContact);

        miAboutUs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.META_DOWN_MASK));
        miAboutUs.setMnemonic('A');
        miAboutUs.setText("About");
        miAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutUsActionPerformed(evt);
            }
        });
        jMenu2.add(miAboutUs);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutUsActionPerformed
        MessageUtils.showInformationMessage("About Us", "Movie Cinema Application 1.0");
    }//GEN-LAST:event_miAboutUsActionPerformed

    private void miContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContactActionPerformed
        MessageUtils.showInformationMessage("Contact Info", "Email contact: movieCinemaApp@mail.com");
    }//GEN-LAST:event_miContactActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        logout();
    }//GEN-LAST:event_miLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MovieManager().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miAboutUs;
    private javax.swing.JMenuItem miContact;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JTabbedPane tpContent;
    // End of variables declaration//GEN-END:variables

    private void setDisplay(User user) {
        if (user.getUserName().equals(ADMIN)) {
            tpContent.add(ADMIN, new UploadMoviePanel());
        } else {
            tpContent.add("Edit Actor-Director", new EditActorDirectorPanel());
            tpContent.add("Edit Movie", new EditMoviePanel());
            tpContent.add("Drag_nd_Drop", new DragAndDropPanel());
        }
    }

    private void logout() {
        boolean dialogResult = MessageUtils.showConfirmDialog("Logout", "Logout??? You serious??");
        if(dialogResult){
            this.dispose();
            OpeningPage openingPage = new OpeningPage();
            openingPage.setVisible(true);
        }
    }
}
